using System;
using System.Collections.Generic;
using System.Globalization;

namespace AdofaiRichPresence.Core {
    // No global mutable language: each caller uses its saved Settings.Language.
    internal static class Localization {
        private static readonly Dictionary<string, string> English = new Dictionary<string, string>(StringComparer.Ordinal) {
            { "표시 정보", "Display" },
            { "동작 방식", "Behavior" },
            { "Discord 연결", "Connection" },
            { "이미지", "Images" },
            { "디버그", "Debug" },
            { "설정을 바꾼 뒤 Unity Mod Manager의 저장 버튼을 눌러 변경사항을 보존하세요.", "Changes apply immediately. Click Save in Unity Mod Manager to keep them." },
            { "기본 설정 전체 복원", "Reset all settings" },
            { "복원 취소", "Undo reset" },
            { "Discord 연결, CDN 주소와 비밀키를 포함한 모든 설정을 기본값으로 바꿉니다.", "Reset all settings, including the Discord connection, CDN URL and upload secret." },
            { "복원 실행", "Reset now" },
            { "취소", "Cancel" },
            { "복원 취소를 누르면 직전 설정으로 돌아갑니다. 변경사항은 즉시 적용되며, 보존하려면 저장하세요.", "Undo reset restores your previous settings. Changes apply immediately; click Save to keep them." },
            { "Discord 상태 메시지에 표시할 정보를 고르세요.", "Choose what to show in your Discord activity." },
            { "상태 줄은 Discord 글자 수 제한에 맞춰 자동으로 줄어들 수 있습니다.", "Long activity text may be shortened to fit Discord's character limit." },
            { "추천 설정", "Recommended" },
            { "간단히 보기", "Minimal" },
            { "핵심 정보", "Basic information" },
            { " 레벨/곡 이름 & 아티스트 & 제작자", " Level / song title, artist and creator" },
            { " 진행률 (%)", " Progress (%)" },
            { " 메뉴/일시정지/에디터 등 상태", " Activity state (menu, paused, editor, etc.)" },
            { "세부 정보", "Details" },
            { " 정확도 (%)", " Accuracy (%)" },
            { " X-정확도 (%, 더 엄격한 기준)", " X-Accuracy (%, stricter scoring)" },
            { " 남은 타일 수", " Remaining tiles" },
            { " 난이도", " Difficulty" },
            { " 경과 시간 / 곡 길이", " Elapsed time / song length" },
            { " 체크포인트 사용 횟수", " Checkpoints used" },
            { "미리보기 (예시 맵)", "Preview (example level)" },
            { "현재 선택한 표시 옵션이 Discord의 두 줄에 어떻게 보이는지 보여줍니다.", "An example of the two activity lines with your current display options." },
            { "예시 맵 - Example Artist", "Example Level - Example Artist" },
            { "플레이 중", "Playing" },
            { "듣는 중", "Listening" },
            { "남은 580/1000 타일", "580/1000 tiles left" },
            { "정확도 98.42%", "Accuracy 98.42%" },
            { "X-정확도 97.80%", "X-Accuracy 97.80%" },
            { "체크포인트 2회", "Checkpoints: 2" },
            { "난이도 8/10", "Difficulty 8/10" },
            { "제작: Example Creator", "By: Example Creator" },
            { "(표시할 상태 정보 없음)", "(No activity details selected)" },
            { "상세: ", "Details: " },
            { "상태: ", "State: " },
            { "글자 수: 상세 {0}/128, 상태 {1}/128", "Characters: details {0}/128, state {1}/128" },
            { "상태 줄이 길어 Discord에서 끝부분이 잘립니다. 표시 항목을 줄여 보세요.", "The activity line will be truncated. Select fewer details to shorten it." },
            { "클리어 시 상세 결과가 별도 상태 줄에 표시됩니다.", "Detailed results appear in the activity state after a clear." },
            { "표시 방식", "Activity behavior" },
            { "플레이 중인 정보와 완료 결과를 Discord에 어떻게 보여줄지 정합니다.", "Choose how gameplay and results appear on Discord." },
            { "활동 유형", "Activity type" },
            { " \"플레이 중\" 대신 \"듣는 중\"으로 표시", " Show as \"Listening\" instead of \"Playing\"" },
            { "이미지와 링크", "Images and links" },
            { " 맵 커버 이미지를 로고로 자동 사용 (워크샵 레벨만 지원)", " Use the level cover image automatically (Workshop levels only)" },
            { "  커버 이미지는 CDN 탭의 업로드 주소로 한 번 업로드됩니다.", "  Cover images are uploaded to the URL configured in the CDN tab." },
            { " \"이 모드 받기\" 버튼 표시", " Show the \"Get this mod\" button" },
            { "  버튼은 기본적으로 숨겨져 있으며, 켜면 Discord 상태에 GitHub 링크가 추가됩니다.", "  Off by default. Adds a GitHub download link to your Discord activity." },
            { " 레벨 완료 시 상세 결과(정확도 등) 표시", " Show detailed results (accuracy, etc.) after a clear" },
            { "기본 Application ID가 포함되어 있어 보통은 입력하지 않아도 됩니다.", "A default Application ID is included; you usually do not need to change it." },
            { "자신의 Discord 앱과 Art Assets를 사용하려는 경우에만 바꾸세요.", "Change it only if you want to use your own Discord app and Art Assets." },
            { "연결 상태: ", "Connection: " },
            { "초기화 중", "Initializing" },
            { "Discord 다시 연결", "Reconnect Discord" },
            { " Discord 상태 표시 사용", " Enable Discord activity" },
            { "  Discord 연결을 중지하고 게임 기본 Discord 표시를 다시 사용합니다.", "  Stops this mod's connection and restores the game's built-in Discord activity." },
            { "Application ID (숫자만)", "Application ID (digits only)" },
            { "기본 ID로 되돌리기", "Restore default ID" },
            { "Discord 개발자 포털에서 확인할 수 있습니다.", "Find this in the Discord Developer Portal." },
            { "Application ID가 비어 있습니다. 상태 표시를 사용하려면 ID를 입력하세요.", "Application ID is empty. Enter an ID to enable activity." },
            { "Application ID는 숫자만 입력해야 합니다.", "Application ID must contain digits only." },
            { " 게임 기본 Discord 표시 끄기 (권장, 충돌 방지)", " Disable the game's built-in Discord activity (recommended)" },
            { "  이 모드의 표시와 게임 기본 표시가 서로 덮어쓰는 문제를 줄입니다.", "  Prevents this mod and the game from overwriting each other's activity." },
            { "업데이트 주기: {0}초", "Update interval: {0} seconds" },
            { "  짧게 하면 더 빠르게 갱신되지만 게임과 Discord의 작업량이 늘어납니다.", "  Shorter intervals refresh faster but increase game and Discord workload." },
            { "큰 이미지", "Large image" },
            { "Discord 개발자 포털의 Rich Presence → Art Assets에 등록한 키를 입력하세요.", "Enter keys from Rich Presence > Art Assets in the Discord Developer Portal." },
            { "비워 두면 해당 상태는 기본 이미지로 대체됩니다.", "Leave a state key empty to use the default image." },
            { "기본:", "Default:" },
            { "일시정지:", "Paused:" },
            { "메뉴:", "Menu:" },
            { "에디터:", "Editor:" },
            { "작은 아이콘 (선택사항)", "Small icons (optional)" },
            { "키가 없거나 등록되지 않은 이미지는 Discord에서 표시되지 않을 수 있습니다.", "Empty or unregistered image keys may not appear on Discord." },
            { "플레이 중:", "Playing:" },
            { "죽음:", "Failed:" },
            { "맵 커버 이미지 CDN", "Level cover image CDN" },
            { "동작 방식 탭에서 커버 이미지 자동 사용을 켰을 때만 사용됩니다.", "Used only when automatic cover images are enabled in the Behavior tab." },
            { "커버 이미지는 입력한 서버로 업로드되므로, 신뢰할 수 있는 주소만 사용하세요.", "Cover images are uploaded to this server. Only use a URL you trust." },
            { "커버 이미지 자동 사용이 켜져 있지만 업로드 URL이 비어 있습니다.", "Automatic cover images are enabled, but the upload URL is empty." },
            { "업로드 설정", "Upload settings" },
            { "업로드 URL:", "Upload URL:" },
            { "비밀키:", "Secret:" },
            { "비밀키는 서버가 요구할 때만 입력하세요. 기본 서버는 비밀키 없이 사용할 수 있습니다.", "Enter a secret only if required by your server. The default server does not require one." },
            { "문제 해결", "Troubleshooting" },
            { " 디버그 로그 (문제 생겼을 때만 켜세요)", " Debug logging (enable only when troubleshooting)" },
            { "  UMM 로그에 게임 상태와 Discord 연결 정보를 추가합니다. 평소에는 꺼 두는 것을 권장합니다.", "  Adds game state and connection details to UMM logs. Leave off during normal use." },
            { "사용 안 함", "Disabled" },
            { "연결됨", "Connected" },
            { "오류: ", "Error: " },
            { "연결 대기 중", "Waiting to connect" },
            { "연결 시도 중", "Connecting" },
            { "죽음", "Failed" },
            { "일시정지", "Paused" },
            { "레벨 에디터: ", "Level editor: " },
            { "제작 중", "Editing" },
            { "클리어: ", "Cleared: " },
            { "완료!", "Complete!" },
            { "레벨 선택 중", "Selecting a level" },
            { "메인 메뉴", "Main menu" },
            { "워크샵에서 보기", "View on Workshop" },
            { "이 모드 받기", "Get this mod" },
            { "정확도 ", "Accuracy " },
            { "X-정확도 ", "X-Accuracy " },
            { "정확 {0}  빠름 {1}  느림 {2}", "Perfect {0}  Early {1}  Late {2}" },
            { "체크포인트 {0}회", "Checkpoints: {0}" },
            { "난이도 ", "Difficulty " },
            { "제작: ", "By: " },
            { " 타일", " tiles" },
            { "남은 {0}/{1} 타일", "{0}/{1} tiles left" },
            { "Discord RPC 호출 실패: {0}", "Discord RPC callback failed: {0}" },
            { "Discord RPC 연결이 끊겼습니다.", "Discord RPC disconnected." },
            { "Discord 상태 전송 실패: {0}", "Failed to send Discord activity: {0}" },
            { "Discord RPC 파이프 연결 실패 (파이프 {0})", "Discord RPC pipe connection failed (pipe {0})" },
            { "Discord RPC 오류 ({0}): {1}", "Discord RPC error ({0}): {1}" },
        };

        internal static string NormalizeLanguage(string language) {
            return string.Equals(language?.Trim(), "en", StringComparison.OrdinalIgnoreCase) ? "en" : "ko";
        }

        internal static string Text(string language, string korean) {
            if (korean == null) return "";
            return NormalizeLanguage(language) == "en" && English.TryGetValue(korean, out string english)
                ? english : korean;
        }

        internal static string Format(string language, string korean, params object[] args) {
            return string.Format(CultureInfo.InvariantCulture, Text(language, korean), args);
        }
    }
}
